{-|
A font in a ROM: unscii 8x8, and the three lines of arithmetic that turn a
character code and a beam position into one pixel.

Unscii is Viznut's bitmapped Unicode font, in the Public Domain
(<http://viznut.fi/unscii/>); "Screen.Font.Unscii8" is the 2 KB of it this board
uses, generated by @tools\/unscii.py@. Only its @unscii-16-full@ variant is GPL, for
incorporating GNU Unifont glyphs -- the 8x8 one this uses is not that variant.

__Why 8x8 rather than the 8x16 a PC used.__ Two reasons, and the first is the one
that shows up in a timing report. With 256 glyphs of eight rows, the ROM address for
row @r@ of glyph @c@ is @c * 8 + r@, and because eight is a power of two that
multiply is a shift is a bit concatenation: 'glyphAddr' is @c ++# r@ and costs no
logic whatsoever. A 14-row cell, as EGA used, puts a real multiplier in the pixel
path -- which is 'Ascii.steps''s lesson in a new place. The second reason is that
8x8 is what arcade boards and the NES used for a tile, so it is the cell size the
look actually comes from; 8x16 reads as a DOS terminal.

__What it costs.__ 2048 bytes is 16 Kb, which is one RAMB18E1 of the fifty-odd this
part has. An 80x60 grid of character codes is another 4800 bytes, so a whole text
mode is two block RAMs and a few comparators -- around 4% of the device, and the
cheapest way there is to put something legible on a screen.

__What it costs in time, which is nothing.__ 'glyphRow' is a synchronous ROM, so it
answers a cycle after it is asked. That is free here: 'Basys3.dot' makes a pixel four
clock cycles long, and a constant delay on the colour path relative to the syncs is
a constant horizontal shift, so one cycle is a quarter of a pixel. A design that
reads its character codes from a second block RAM spends another cycle and is still
only half a pixel out. Anything under four cycles is sub-pixel and invisible; at
four it is a whole pixel and the address has to start leading the beam instead.

__The one number that is not a power of two.__ A character map is indexed by
@cellY * columns + cellX@, and at 640 pixels wide @columns@ is 80 -- so that index
/is/ a multiply, unlike everything above. 80 is 64 + 16, so it is two shifts and an
adder, which is cheap; or pad the stride to 128 and the address goes back to being
@cellY ++# cellX@ at the price of a third of the map being unused. Which of those is
right depends on how many block RAMs are left, so this module does not choose:
'cellAt' hands over the two cell coordinates and the design addresses its own memory.

Not re-exported by "Basys3.Board", for the reason the @Pmod@ modules are not: a font
ROM is a block RAM a design decided to spend, so a design that draws text says so in
an import. It would also take the words 'ink' and 'within', which are too good to
spend on a module most designs do not use.
-}
module Screen.Font
  ( -- * The font
    unscii8
    -- * Where the beam is in the text grid
  , cellAt
  , within
    -- * Reading a glyph
  , glyphAddr
  , glyphRow
  , ink
  , inkAt
  ) where

import Clash.Prelude

import Protocol.VGA        (Coord)
import Screen.Font.Unscii8 (glyphBytes)

-- | The font as a ROM's worth of bytes: 256 glyphs of eight rows, glyph-major and
-- top row first. 'glyphRow' is this behind an address.
--
-- A 'MemBlob' rather than a @Vec 2048 (BitVector 8)@ because that is the form
-- Clash carries efficiently through compilation and emits as a block RAM's
-- initial contents -- a 2048-element 'Vec' literal is the same data and a much
-- slower build.
unscii8 :: MemBlob 2048 8
unscii8 = $(memBlobTH Nothing glyphBytes)

-- | Which 8x8 cell a beam position falls in: @'cellAt' (12, 20)@ is @(1, 2)@.
--
-- Applied to a picture's size rather than a position it gives the grid instead, so
-- @'cellAt' (640, 480)@ is the @(80, 60)@ cells a 640x480 screen holds.
cellAt :: (Coord, Coord) -> (Coord, Coord)
cellAt (x, y) = (shiftR x 3, shiftR y 3)

-- | How far into its cell a coordinate is, along either axis: the low three bits,
-- which is a column of a glyph when it comes from x and a row of one when it comes
-- from y.
within :: Coord -> BitVector 3
within = truncateB . pack

-- | Where row @y@ of glyph @code@ lives in 'unscii8'.
--
-- The whole of it is @code ++# 'within' y@. Eight rows to a glyph makes @code * 8@
-- a three-bit shift, and a shift by a constant followed by an or is a
-- concatenation, so this is a renaming of wires and not arithmetic at all. It is
-- also why the row has to come from the beam's y directly rather than from
-- 'cellAt': 'cellAt' throws away exactly the three bits this needs.
glyphAddr :: BitVector 8 -> Coord -> Unsigned 11
glyphAddr code y = bitCoerce (code ++# within y)

-- | The font ROM: one row of eight pixels, one cycle after its address.
--
-- Synchronous, so it infers a block RAM. An asynchronous ROM of the same contents
-- would be 2048 entries of distributed RAM, which is hundreds of LUTs to save a
-- cycle that -- see the module header -- there is no need to save.
glyphRow
  :: (HiddenClock dom, HiddenEnable dom)
  => Signal dom (Unsigned 11)
  -- ^ From 'glyphAddr'.
  -> Signal dom (BitVector 8)
  -- ^ Eight pixels of one row, most significant bit leftmost.
glyphRow = romBlob unscii8

-- | Whether the beam is on ink or on paper, given the row of the glyph it is
-- crossing and how far across the screen it is.
--
-- Pure, so a test can ask it about a glyph without simulating a ROM, and one 8:1
-- mux in hardware.
ink :: BitVector 8 -> Coord -> Bool
ink row x = bitToBool (bits !! column)
 where
  -- Index 0 of a Vec is the most significant bit of the BitVector it unpacks
  -- from, which is the leftmost pixel -- so no eight-minus-x appears anywhere.
  bits = unpack row :: Vec 8 Bit

  column :: Index 8
  column = bitCoerce (within x)

-- | The whole lookup: given the character code of the cell the beam is in and
-- where the beam is, whether this pixel is ink.
--
-- @
-- paint beam = 'Screen.mono' \<$\> 'inkAt' code pos
--  where
--   pos  = somewhere . 'Protocol.VGA.scanAt' \<$\> beam
--   code = charMap ('cellAt' \<$\> pos)   -- the design's own memory
--
--   somewhere (Just p) = p
--   somewhere Nothing  = (0, 0)   -- blanked, and 'Basys3.vgaPins' will black it
-- @
--
-- The ROM's cycle of latency is inside this, and is a quarter of a pixel: see the
-- module header for why that is not something to correct for.
inkAt
  :: (HiddenClock dom, HiddenEnable dom)
  => Signal dom (BitVector 8)
  -- ^ The code of the cell the beam is in.
  -> Signal dom (Coord, Coord)
  -- ^ Where the beam is, from 'Protocol.VGA.scanAt'.
  -> Signal dom Bool
inkAt code pos =
  ink <$> glyphRow (glyphAddr <$> code <*> (snd <$> pos)) <*> (fst <$> pos)
