#!/usr/bin/env python3
"""Turn unscii-8.hex into src/Screen/Font/Unscii8.hs.

Unscii is Viznut's bitmapped Unicode font, and unscii-8 is its 8x8 variant.  It is
in the Public Domain -- only "unscii-16-full" is GPL, because that one incorporates
GNU Unifont glyphs.  Upstream:

    http://viznut.fi/unscii/
    http://viznut.fi/unscii/unscii-8.hex

The output is generated and checked in, rather than the .hex being read at compile
time by Template Haskell.  Three reasons: the font is 2 KB of the upstream file's
60 KB, so checking in only what is used is smaller than checking in the source; a
TH splice that does file IO has to get its path right relative to whatever the
compiler's working directory happens to be, which is one more thing to break; and a
generated Haskell literal needs no build-time dependency at all, so `make repl`,
`stack build` and Clash all see exactly the same bytes.  The cost is that the file
has to be regenerated by hand, which is what this script and `make font` are for.

Only codepoints U+0000..U+00FF are taken, because the ROM is indexed by a byte.
That is Latin-1, and unscii covers all of it.  Unifont .hex records a glyph as
`CODEPOINT:HEXDIGITS`, two hex digits per row, so a 16-digit record is an 8x8 glyph
and a 32-digit one is 8x16 or double width.  Anything that is not 16 digits is
emitted blank -- in this range that is only U+0000, a control character nobody
draws.

Row order is top to bottom and the most significant bit of each row is the leftmost
pixel, both of which the .hex format already does, so no bit twiddling happens here
at all.  Glyphs are emitted glyph-major, which is what makes the ROM address a bit
concatenation rather than a multiply: `code ++# row`.

Usage:
    tools/unscii.py unscii-8.hex > src/Screen/Font/Unscii8.hs
    curl -sL http://viznut.fi/unscii/unscii-8.hex | tools/unscii.py - > ...
"""

import sys

HEIGHT = 8
GLYPHS = 256

HEADER = '''-- | Generated by @tools\\/unscii.py@ from unscii-8.hex -- do not edit.
--
-- Unscii 8x8, by Viznut, in the Public Domain: <http://viznut.fi/unscii/>. This is
-- codepoints U+0000 to U+00FF of it, which is Latin-1 and is what a ROM indexed by
-- a byte can hold.
--
-- {glyphs} glyphs of {height} rows, glyph-major and top row first, so glyph @c@ row @r@ is
-- at index @c * {height} + r@ -- which "Screen.Font" reaches as @c ++# r@ rather than with a
-- multiplier. The most significant bit of a row is its leftmost pixel.
--
-- Split out from "Screen.Font" so that the 2 KB of data and the ten lines that read
-- it are not in the same file, and so regenerating the font touches nothing that
-- was written by hand.
module Screen.Font.Unscii8
  ( glyphBytes
  ) where

import Clash.Prelude

-- | The whole font, {total} bytes of it, in the order 'Screen.Font.unscii8' wants.
glyphBytes :: [BitVector {height}]
glyphBytes =
'''


def load(stream):
    """Codepoint -> list of row bytes, for the 8x8 records only."""
    glyphs = {}
    for line in stream:
        line = line.strip()
        if not line or ":" not in line:
            continue
        code, digits = line.split(":", 1)
        if len(digits) != 2 * HEIGHT:
            continue
        glyphs[int(code, 16)] = [
            int(digits[i:i + 2], 16) for i in range(0, len(digits), 2)
        ]
    return glyphs


def label(code):
    """How a glyph's comment names it: the character itself when that is legible."""
    if 0x21 <= code <= 0x7E:
        return "U+%04X '%s'" % (code, chr(code))
    if code == 0x20:
        return "U+0020 space"
    return "U+%04X" % code


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else "-"
    with (sys.stdin if path == "-" else open(path)) as f:
        glyphs = load(f)

    missing = [c for c in range(GLYPHS) if c not in glyphs]
    if missing:
        print("unscii.py: %d of the first %d codepoints have no 8x8 glyph, blanking "
              "them: %s" % (len(missing), GLYPHS,
                            " ".join("U+%04X" % c for c in missing)),
              file=sys.stderr)

    out = [HEADER.format(glyphs=GLYPHS, height=HEIGHT, total=GLYPHS * HEIGHT)]
    for code in range(GLYPHS):
        rows = glyphs.get(code, [0] * HEIGHT)
        lead = "  [ " if code == 0 else "  , "
        out.append("  -- %s\n%s%s\n"
                   % (label(code), lead,
                      ", ".join("0x%02X" % b for b in rows)))
    out.append("  ]\n")
    sys.stdout.write("".join(out))


if __name__ == "__main__":
    main()
